name: widgets_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.3
  cupertino_icons: ^1.0.6
  go_router: ^14.2.1
  animate_do: ^3.3.4

dev_dependencies:
  custom_lint:
  riverpod_lint: ^2.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
